/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const COLOR_PRESETS: typeof import('../composables/useAppConfig').COLOR_PRESETS
  const EffectScope: typeof import('vue').EffectScope
  const FONT_OPTIONS: typeof import('../composables/useAppConfig').FONT_OPTIONS
  const RADIUS_OPTIONS: typeof import('../composables/useAppConfig').RADIUS_OPTIONS
  const computed: typeof import('vue').computed
  const confirmState: typeof import('../composables/useConfirm').confirmState
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const definePage: typeof import('vue-router/experimental').definePage
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getWsColor: typeof import('../stores/workspace').getWsColor
  const getWsInitials: typeof import('../stores/workspace').getWsInitials
  const h: typeof import('vue').h
  const hasToken: typeof import('../stores/user').hasToken
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAction: typeof import('../composables/useApi').useAction
  const useAppConfig: typeof import('../composables/useAppConfig').useAppConfig
  const useAttrs: typeof import('vue').useAttrs
  const useConfirm: typeof import('../composables/useConfirm').useConfirm
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useMonitorStore: typeof import('../stores/monitor').useMonitorStore
  const useNavbarStore: typeof import('../stores/pages/topNavbar').useNavbarStore
  const usePeerPageStore: typeof import('../stores/peerPage').usePeerPageStore
  const usePolicyPageStore: typeof import('../stores/usePolicyPageStore').usePolicyPageStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSystemTheme: typeof import('../composables/use-system-theme').useSystemTheme
  const useTable: typeof import('../composables/useApi').useTable
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('../composables/useTheme').useTheme
  const useThemeStore: typeof import('../stores/useTheme').useThemeStore
  const useTopologyStore: typeof import('../stores/topology').useTopologyStore
  const useUserDashboardStore: typeof import('../stores/useDashboard').useUserDashboardStore
  const useUserSettingsStore: typeof import('../stores/pages/userSettings').useUserSettingsStore
  const useUserStore: typeof import('../stores/user').useUserStore
  const useWorkspacePageStore: typeof import('../stores/workspacePage').useWorkspacePageStore
  const useWorkspaceStore: typeof import('../stores/workspace').useWorkspaceStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Theme, ColorScheme, RadiusValue, FontFamily, AppConfig } from '../composables/useAppConfig'
  import('../composables/useAppConfig')
  // @ts-ignore
  export type { MetricCard, TopoNode, TopoLink, WorkspaceCard, NetworkEvent } from '../stores/useDashboard'
  import('../stores/useDashboard')
  // @ts-ignore
  export type { User } from '../stores/user'
  import('../stores/user')
  // @ts-ignore
  export type { Workspace } from '../stores/workspace'
  import('../stores/workspace')
}
