/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/ecommerce/customers/': RouteRecordInfo<
      '/apps/ecommerce/customers/',
      '/apps/ecommerce/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/workspaces/': RouteRecordInfo<
      '/apps/workspaces/',
      '/apps/workspaces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/login/'
      | '/auth/signup/'
    >,
    '/auth/login/': RouteRecordInfo<
      '/auth/login/',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/signup/': RouteRecordInfo<
      '/auth/signup/',
      '/auth/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/members/': RouteRecordInfo<
      '/manage/members/',
      '/manage/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/monitor/': RouteRecordInfo<
      '/manage/monitor/',
      '/manage/monitor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/nodes/': RouteRecordInfo<
      '/manage/nodes/',
      '/manage/nodes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/peers/': RouteRecordInfo<
      '/manage/peers/',
      '/manage/peers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/policies/': RouteRecordInfo<
      '/manage/policies/',
      '/manage/policies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/stepper/': RouteRecordInfo<
      '/manage/stepper/',
      '/manage/stepper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/tokens/': RouteRecordInfo<
      '/manage/tokens/',
      '/manage/tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/topology/': RouteRecordInfo<
      '/manage/topology/',
      '/manage/topology',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/workspaces/': RouteRecordInfo<
      '/manage/workspaces/',
      '/manage/workspaces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/account/': RouteRecordInfo<
      '/user/account/',
      '/user/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/billing/': RouteRecordInfo<
      '/user/billing/',
      '/user/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/notifications/': RouteRecordInfo<
      '/user/notifications/',
      '/user/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/profile/': RouteRecordInfo<
      '/user/profile/',
      '/user/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/apps/ecommerce/customers/index.vue': {
      routes:
        | '/apps/ecommerce/customers/'
      views:
        | never
    }
    'src/pages/apps/workspaces/index.vue': {
      routes:
        | '/apps/workspaces/'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/login/'
        | '/auth/signup/'
      views:
        | 'default'
    }
    'src/pages/auth/login/index.vue': {
      routes:
        | '/auth/login/'
      views:
        | never
    }
    'src/pages/auth/signup/index.vue': {
      routes:
        | '/auth/signup/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/manage/members/index.vue': {
      routes:
        | '/manage/members/'
      views:
        | never
    }
    'src/pages/manage/monitor/index.vue': {
      routes:
        | '/manage/monitor/'
      views:
        | never
    }
    'src/pages/manage/nodes/index.vue': {
      routes:
        | '/manage/nodes/'
      views:
        | never
    }
    'src/pages/manage/peers/index.vue': {
      routes:
        | '/manage/peers/'
      views:
        | never
    }
    'src/pages/manage/policies/index.vue': {
      routes:
        | '/manage/policies/'
      views:
        | never
    }
    'src/pages/manage/stepper/index.vue': {
      routes:
        | '/manage/stepper/'
      views:
        | never
    }
    'src/pages/manage/tokens/index.vue': {
      routes:
        | '/manage/tokens/'
      views:
        | never
    }
    'src/pages/manage/topology/index.vue': {
      routes:
        | '/manage/topology/'
      views:
        | never
    }
    'src/pages/manage/workspaces/index.vue': {
      routes:
        | '/manage/workspaces/'
      views:
        | never
    }
    'src/pages/user/account/index.vue': {
      routes:
        | '/user/account/'
      views:
        | never
    }
    'src/pages/user/billing/index.vue': {
      routes:
        | '/user/billing/'
      views:
        | never
    }
    'src/pages/user/notifications/index.vue': {
      routes:
        | '/user/notifications/'
      views:
        | never
    }
    'src/pages/user/profile/index.vue': {
      routes:
        | '/user/profile/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
