app-id: macbook-pro.local
enable-wrrp: false
help: false
level: debug
listen: :8080
management-url: http://wireflow.run
save: true
server-url: ""
show-system-log: false
signaling-url: nats://signaling.wireflow.run:4222
token: 36q6GrlfXRzMFVC4
turnserver-url: stun.wireflow.run:3478
version: false
wrrper-url: 81.68.109.143:6266
