// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: signaling/grpc/signaling/signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MessageDirectOfferType MessageType = 0
	MessageType_MessageRelayOfferType  MessageType = 1
	MessageType_MessageForwardType     MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MessageDirectOfferType",
		1: "MessageRelayOfferType",
		2: "MessageForwardType",
	}
	MessageType_value = map[string]int32{
		"MessageDirectOfferType": 0,
		"MessageRelayOfferType":  1,
		"MessageForwardType":     2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_grpc_signaling_signaling_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_signaling_grpc_signaling_signaling_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_signaling_grpc_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

// ControlMessage is dynamic message for kind to request and response
type EncryptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Encrypt       int32                  `protobuf:"varint,3,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptMessage) Reset() {
	*x = EncryptMessage{}
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMessage) ProtoMessage() {}

func (x *EncryptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMessage.ProtoReflect.Descriptor instead.
func (*EncryptMessage) Descriptor() ([]byte, []int) {
	return file_signaling_grpc_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptMessage) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *EncryptMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EncryptMessage) GetEncrypt() int32 {
	if x != nil {
		return x.Encrypt
	}
	return 0
}

func (x *EncryptMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EncryptMessageReqAndResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPublicKey  string                 `protobuf:"bytes,1,opt,name=srcPublicKey,proto3" json:"srcPublicKey,omitempty"`
	DstPublicKey  string                 `protobuf:"bytes,2,opt,name=dstPublicKey,proto3" json:"dstPublicKey,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Type          MessageType            `protobuf:"varint,6,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptMessageReqAndResp) Reset() {
	*x = EncryptMessageReqAndResp{}
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptMessageReqAndResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMessageReqAndResp) ProtoMessage() {}

func (x *EncryptMessageReqAndResp) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_grpc_signaling_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMessageReqAndResp.ProtoReflect.Descriptor instead.
func (*EncryptMessageReqAndResp) Descriptor() ([]byte, []int) {
	return file_signaling_grpc_signaling_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptMessageReqAndResp) GetSrcPublicKey() string {
	if x != nil {
		return x.SrcPublicKey
	}
	return ""
}

func (x *EncryptMessageReqAndResp) GetDstPublicKey() string {
	if x != nil {
		return x.DstPublicKey
	}
	return ""
}

func (x *EncryptMessageReqAndResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EncryptMessageReqAndResp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EncryptMessageReqAndResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EncryptMessageReqAndResp) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MessageDirectOfferType
}

var File_signaling_grpc_signaling_signaling_proto protoreflect.FileDescriptor

var file_signaling_grpc_signaling_signaling_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0e, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xc4, 0x01, 0x0a, 0x18, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x73, 0x74, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x5c, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x6c, 0x61, 0x79, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02, 0x32, 0x75, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x07, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x0f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x22,
	0x5a, 0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x61, 0x6e, 0x79, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signaling_grpc_signaling_signaling_proto_rawDescOnce sync.Once
	file_signaling_grpc_signaling_signaling_proto_rawDescData = file_signaling_grpc_signaling_signaling_proto_rawDesc
)

func file_signaling_grpc_signaling_signaling_proto_rawDescGZIP() []byte {
	file_signaling_grpc_signaling_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_grpc_signaling_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(file_signaling_grpc_signaling_signaling_proto_rawDescData)
	})
	return file_signaling_grpc_signaling_signaling_proto_rawDescData
}

var file_signaling_grpc_signaling_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signaling_grpc_signaling_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signaling_grpc_signaling_signaling_proto_goTypes = []any{
	(MessageType)(0),                 // 0: MessageType
	(*EncryptMessage)(nil),           // 1: EncryptMessage
	(*EncryptMessageReqAndResp)(nil), // 2: EncryptMessageReqAndResp
}
var file_signaling_grpc_signaling_signaling_proto_depIdxs = []int32{
	0, // 0: EncryptMessageReqAndResp.type:type_name -> MessageType
	1, // 1: SignalingService.Register:input_type -> EncryptMessage
	1, // 2: SignalingService.Forward:input_type -> EncryptMessage
	1, // 3: SignalingService.Register:output_type -> EncryptMessage
	1, // 4: SignalingService.Forward:output_type -> EncryptMessage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_signaling_grpc_signaling_signaling_proto_init() }
func file_signaling_grpc_signaling_signaling_proto_init() {
	if File_signaling_grpc_signaling_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signaling_grpc_signaling_signaling_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_grpc_signaling_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_grpc_signaling_signaling_proto_depIdxs,
		EnumInfos:         file_signaling_grpc_signaling_signaling_proto_enumTypes,
		MessageInfos:      file_signaling_grpc_signaling_signaling_proto_msgTypes,
	}.Build()
	File_signaling_grpc_signaling_signaling_proto = out.File
	file_signaling_grpc_signaling_signaling_proto_rawDesc = nil
	file_signaling_grpc_signaling_signaling_proto_goTypes = nil
	file_signaling_grpc_signaling_signaling_proto_depIdxs = nil
}
