---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowclusterpeerings
  - wireflowenrollmenttokens
  - wireflownetworkpeerings
  - wireflownetworks
  - wireflowpeers
  - wireflowpolicies
  - wireflowrelayservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowclusterpeerings/finalizers
  - wireflowenrollmenttokens/finalizers
  - wireflownetworkpeerings/finalizers
  - wireflownetworks/finalizers
  - wireflowpeers/finalizers
  - wireflowpolicies/finalizers
  - wireflowrelayservers/finalizers
  verbs:
  - update
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowclusterpeerings/status
  - wireflowenrollmenttokens/status
  - wireflownetworkpeerings/status
  - wireflownetworks/status
  - wireflowpeers/status
  - wireflowpolicies/status
  - wireflowrelayservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wireflowcontroller.wireflow.run
  resources:
  - wireflowclusters
  verbs:
  - get
  - list
  - watch
