database:
  driver: "sqlite"
  dsn: "root:root@tcp(127.0.0.1:3306)/wireflow?charset=utf8mb4&parseTime=True&loc=Local"

dex:
  issur: http://localhost:5556/dex/auth
  providerUrl: http://localhost:5556/dex

monitor:
  address: http://101.36.119.12:8428

signaling:
  signalAddress: localhost:4222