database:
  driver: "sqlite"
  dsn: wireflow.db

#dex:
#  issur: http://localhost:5556/dex/auth
#  providerUrl: http://localhost:5556/dex

telemetry:
  vmEndpoint: http://101.36.119.12:8428/api/v1/write

signaling-url: nats://localhost:4222