database:
    driver: mysql
    dsn: root:root@tcp(wireflow-mariadb.wireflow-system.svc.cluster.local:3306)/wireflow?charset=utf8mb4&parseTime=True&loc=Local
dex:
    providerurl: http://wireflow-dex.wireflow-system.svc.cluster.local:5556
env: dev
health-probe-bind-address: :8081
level: info
listen: :8080
metrics-addr: :8443
monitor:
    address: ""
port: 3478
server-url: http://wireflow.run
signaling-url: nats://wireflow-nats-service.wireflow-system.svc.cluster.local:4222
stun-url: stun.wireflow.run:3478
wrrper-url: :6266

