// Copyright 2025 The Wireflow Authors, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: drp.proto

package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DrpServer_HandleMessage_FullMethodName = "/DrpServer/HandleMessage"
)

// DrpServerClient is the client API for DrpServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type DrpServerClient interface {
	HandleMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DrpMessage, DrpMessage], error)
}

type drpServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDrpServerClient(cc grpc.ClientConnInterface) DrpServerClient {
	return &drpServerClient{cc}
}

func (c *drpServerClient) HandleMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DrpMessage, DrpMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DrpServer_ServiceDesc.Streams[0], DrpServer_HandleMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DrpMessage, DrpMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrpServer_HandleMessageClient = grpc.BidiStreamingClient[DrpMessage, DrpMessage]

// DrpServerServer is the server API for DrpServer service.
// All implementations must embed UnimplementedDrpServerServer
// for forward compatibility.
//
// The greeting service definition.
type DrpServerServer interface {
	HandleMessage(grpc.BidiStreamingServer[DrpMessage, DrpMessage]) error
	mustEmbedUnimplementedDrpServerServer()
}

// UnimplementedDrpServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDrpServerServer struct{}

func (UnimplementedDrpServerServer) HandleMessage(grpc.BidiStreamingServer[DrpMessage, DrpMessage]) error {
	return status.Errorf(codes.Unimplemented, "method HandleMessage not implemented")
}
func (UnimplementedDrpServerServer) mustEmbedUnimplementedDrpServerServer() {}
func (UnimplementedDrpServerServer) testEmbeddedByValue()                   {}

// UnsafeDrpServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrpServerServer will
// result in compilation errors.
type UnsafeDrpServerServer interface {
	mustEmbedUnimplementedDrpServerServer()
}

func RegisterDrpServerServer(s grpc.ServiceRegistrar, srv DrpServerServer) {
	// If the following call pancis, it indicates UnimplementedDrpServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DrpServer_ServiceDesc, srv)
}

func _DrpServer_HandleMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DrpServerServer).HandleMessage(&grpc.GenericServerStream[DrpMessage, DrpMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrpServer_HandleMessageServer = grpc.BidiStreamingServer[DrpMessage, DrpMessage]

// DrpServer_ServiceDesc is the grpc.ServiceDesc for DrpServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrpServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DrpServer",
	HandlerType: (*DrpServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleMessage",
			Handler:       _DrpServer_HandleMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "drp.proto",
}
