// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: signal.proto

package grpc

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义信令包类型
type PacketType int32

const (
	PacketType_UNKNOWN       PacketType = 0
	PacketType_HANDSHAKE_SYN PacketType = 1 // 发起握手：你在吗？
	PacketType_HANDSHAKE_ACK PacketType = 2 // 响应握手：我在，可以交换。
	PacketType_OFFER         PacketType = 3 // 业务数据：Offer
	PacketType_ANSWER        PacketType = 4 //
	PacketType_MESSAGE       PacketType = 5
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HANDSHAKE_SYN",
		2: "HANDSHAKE_ACK",
		3: "OFFER",
		4: "ANSWER",
		5: "MESSAGE",
	}
	PacketType_value = map[string]int32{
		"UNKNOWN":       0,
		"HANDSHAKE_SYN": 1,
		"HANDSHAKE_ACK": 2,
		"OFFER":         3,
		"ANSWER":        4,
		"MESSAGE":       5,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_signal_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_signal_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

type DialerType int32

const (
	DialerType_ICE  DialerType = 0
	DialerType_WRRP DialerType = 1
)

// Enum value maps for DialerType.
var (
	DialerType_name = map[int32]string{
		0: "ICE",
		1: "WRRP",
	}
	DialerType_value = map[string]int32{
		"ICE":  0,
		"WRRP": 1,
	}
)

func (x DialerType) Enum() *DialerType {
	p := new(DialerType)
	*p = x
	return p
}

func (x DialerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialerType) Descriptor() protoreflect.EnumDescriptor {
	return file_signal_proto_enumTypes[1].Descriptor()
}

func (DialerType) Type() protoreflect.EnumType {
	return &file_signal_proto_enumTypes[1]
}

func (x DialerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialerType.Descriptor instead.
func (DialerType) EnumDescriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

type SignalPacket struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     PacketType             `protobuf:"varint,1,opt,name=type,proto3,enum=wireflow.signal.PacketType" json:"type,omitempty"`
	Dialer   DialerType             `protobuf:"varint,2,opt,name=dialer,proto3,enum=wireflow.signal.DialerType" json:"dialer,omitempty"`
	SenderId uint64                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalPacket_Handshake
	//	*SignalPacket_Offer
	//	*SignalPacket_Answer
	//	*SignalPacket_Message
	Payload       isSignalPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalPacket) Reset() {
	*x = SignalPacket{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalPacket) ProtoMessage() {}

func (x *SignalPacket) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalPacket.ProtoReflect.Descriptor instead.
func (*SignalPacket) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_UNKNOWN
}

func (x *SignalPacket) GetDialer() DialerType {
	if x != nil {
		return x.Dialer
	}
	return DialerType_ICE
}

func (x *SignalPacket) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SignalPacket) GetPayload() isSignalPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalPacket) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*SignalPacket_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *SignalPacket) GetOffer() *Offer {
	if x != nil {
		if x, ok := x.Payload.(*SignalPacket_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *SignalPacket) GetAnswer() *Offer {
	if x != nil {
		if x, ok := x.Payload.(*SignalPacket_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *SignalPacket) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Payload.(*SignalPacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isSignalPacket_Payload interface {
	isSignalPacket_Payload()
}

type SignalPacket_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,4,opt,name=handshake,proto3,oneof"`
}

type SignalPacket_Offer struct {
	Offer *Offer `protobuf:"bytes,5,opt,name=offer,proto3,oneof"`
}

type SignalPacket_Answer struct {
	Answer *Offer `protobuf:"bytes,6,opt,name=answer,proto3,oneof"`
}

type SignalPacket_Message struct {
	Message *Message `protobuf:"bytes,7,opt,name=message,proto3,oneof"`
}

func (*SignalPacket_Handshake) isSignalPacket_Payload() {}

func (*SignalPacket_Offer) isSignalPacket_Payload() {}

func (*SignalPacket_Answer) isSignalPacket_Payload() {}

func (*SignalPacket_Message) isSignalPacket_Payload() {}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ufrag         string                 `protobuf:"bytes,1,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	Pwd           string                 `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	TieBreaker    uint64                 `protobuf:"varint,3,opt,name=tieBreaker,proto3" json:"tieBreaker,omitempty"`
	Candidate     string                 `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Vip           string                 `protobuf:"bytes,5,opt,name=vip,proto3" json:"vip,omitempty"`
	Current       []byte                 `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	PublicKey     string                 `protobuf:"bytes,7,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

func (x *Offer) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *Offer) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *Offer) GetTieBreaker() uint64 {
	if x != nil {
		return x.TieBreaker
	}
	return 0
}

func (x *Offer) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Offer) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *Offer) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Offer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// for wrapper Message from api server
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_signal_proto protoreflect.FileDescriptor

var file_signal_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22,
	0xf0, 0x02, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x64, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12,
	0x2e, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12,
	0x30, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x75, 0x66, 0x72, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x66, 0x72,
	0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x77, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x65, 0x42, 0x72, 0x65, 0x61, 0x6b,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x69, 0x65, 0x42, 0x72, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x23, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x29, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x63, 0x0a, 0x0a,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x41, 0x4e, 0x44, 0x53,
	0x48, 0x41, 0x4b, 0x45, 0x5f, 0x53, 0x59, 0x4e, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x41,
	0x4e, 0x44, 0x53, 0x48, 0x41, 0x4b, 0x45, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x4f, 0x46, 0x46, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4e, 0x53, 0x57,
	0x45, 0x52, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10,
	0x05, 0x2a, 0x1f, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x07, 0x0a, 0x03, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x52, 0x52, 0x50,
	0x10, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData = file_signal_proto_rawDesc
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(file_signal_proto_rawDescData)
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_signal_proto_goTypes = []any{
	(PacketType)(0),      // 0: wireflow.signal.PacketType
	(DialerType)(0),      // 1: wireflow.signal.DialerType
	(*SignalPacket)(nil), // 2: wireflow.signal.SignalPacket
	(*Offer)(nil),        // 3: wireflow.signal.Offer
	(*Message)(nil),      // 4: wireflow.signal.Message
	(*Handshake)(nil),    // 5: wireflow.signal.Handshake
}
var file_signal_proto_depIdxs = []int32{
	0, // 0: wireflow.signal.SignalPacket.type:type_name -> wireflow.signal.PacketType
	1, // 1: wireflow.signal.SignalPacket.dialer:type_name -> wireflow.signal.DialerType
	5, // 2: wireflow.signal.SignalPacket.handshake:type_name -> wireflow.signal.Handshake
	3, // 3: wireflow.signal.SignalPacket.offer:type_name -> wireflow.signal.Offer
	3, // 4: wireflow.signal.SignalPacket.answer:type_name -> wireflow.signal.Offer
	4, // 5: wireflow.signal.SignalPacket.message:type_name -> wireflow.signal.Message
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	file_signal_proto_msgTypes[0].OneofWrappers = []any{
		(*SignalPacket_Handshake)(nil),
		(*SignalPacket_Offer)(nil),
		(*SignalPacket_Answer)(nil),
		(*SignalPacket_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signal_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		EnumInfos:         file_signal_proto_enumTypes,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_rawDesc = nil
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
