# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/wireflowcontroller.wireflow.run_wireflowinvitations.yaml
- bases/wireflowcontroller.wireflow.run_wireflownetworks.yaml
- bases/wireflowcontroller.wireflow.run_wireflowpolicies.yaml
- bases/wireflowcontroller.wireflow.run_wireflowpeers.yaml
- bases/wireflowcontroller.wireflow.run_wireflowglobalippools.yaml
- bases/wireflowcontroller.wireflow.run_wireflowendpoints.yaml
- bases/wireflowcontroller.wireflow.run_wireflowsubnetallocations.yaml
- bases/wireflowcontroller.wireflow.run_wireflowenrollmenttokens.yaml
- bases/wireflowcontroller.wireflow.run_wireflowrelayservers.yaml
- bases/wireflowcontroller.wireflow.run_wireflownetworkpeerings.yaml
- bases/wireflowcontroller.wireflow.run_wireflowclusters.yaml
- bases/wireflowcontroller.wireflow.run_wireflowclusterpeerings.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
