// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: management/grpc/mgt/management.proto

package mgt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_Login_FullMethodName       = "/ManagementService/Login"
	ManagementService_Get_FullMethodName         = "/ManagementService/Get"
	ManagementService_List_FullMethodName        = "/ManagementService/List"
	ManagementService_Watch_FullMethodName       = "/ManagementService/Watch"
	ManagementService_Keepalive_FullMethodName   = "/ManagementService/Keepalive"
	ManagementService_VerifyToken_FullMethodName = "/ManagementService/VerifyToken"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Management service definition.
type ManagementServiceClient interface {
	Login(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error)
	Get(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error)
	List(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error)
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagementMessage, ManagementMessage], error)
	Keepalive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagementMessage, ManagementMessage], error)
	// valid token for service
	VerifyToken(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) Login(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementMessage)
	err := c.cc.Invoke(ctx, ManagementService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Get(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementMessage)
	err := c.cc.Invoke(ctx, ManagementService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) List(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementMessage)
	err := c.cc.Invoke(ctx, ManagementService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagementMessage, ManagementMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[0], ManagementService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ManagementMessage, ManagementMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchClient = grpc.BidiStreamingClient[ManagementMessage, ManagementMessage]

func (c *managementServiceClient) Keepalive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagementMessage, ManagementMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[1], ManagementService_Keepalive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ManagementMessage, ManagementMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_KeepaliveClient = grpc.BidiStreamingClient[ManagementMessage, ManagementMessage]

func (c *managementServiceClient) VerifyToken(ctx context.Context, in *ManagementMessage, opts ...grpc.CallOption) (*ManagementMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagementMessage)
	err := c.cc.Invoke(ctx, ManagementService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// The Management service definition.
type ManagementServiceServer interface {
	Login(context.Context, *ManagementMessage) (*ManagementMessage, error)
	Get(context.Context, *ManagementMessage) (*ManagementMessage, error)
	List(context.Context, *ManagementMessage) (*ManagementMessage, error)
	Watch(grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]) error
	Keepalive(grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]) error
	// valid token for service
	VerifyToken(context.Context, *ManagementMessage) (*ManagementMessage, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) Login(context.Context, *ManagementMessage) (*ManagementMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedManagementServiceServer) Get(context.Context, *ManagementMessage) (*ManagementMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedManagementServiceServer) List(context.Context, *ManagementMessage) (*ManagementMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedManagementServiceServer) Watch(grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedManagementServiceServer) Keepalive(grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Keepalive not implemented")
}
func (UnimplementedManagementServiceServer) VerifyToken(context.Context, *ManagementMessage) (*ManagementMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Login(ctx, req.(*ManagementMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Get(ctx, req.(*ManagementMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).List(ctx, req.(*ManagementMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagementServiceServer).Watch(&grpc.GenericServerStream[ManagementMessage, ManagementMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchServer = grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]

func _ManagementService_Keepalive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagementServiceServer).Keepalive(&grpc.GenericServerStream[ManagementMessage, ManagementMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_KeepaliveServer = grpc.BidiStreamingServer[ManagementMessage, ManagementMessage]

func _ManagementService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagementMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).VerifyToken(ctx, req.(*ManagementMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ManagementService_Login_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ManagementService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ManagementService_List_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _ManagementService_VerifyToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ManagementService_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Keepalive",
			Handler:       _ManagementService_Keepalive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "management/grpc/mgt/management.proto",
}
